# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Rei/git_repos/AegisEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Rei/git_repos/AegisEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Rei/git_repos/AegisEngine/CMakeFiles /home/Rei/git_repos/AegisEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Rei/git_repos/AegisEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Aegis2

# Build rule for target.
Aegis2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aegis2
.PHONY : Aegis2

# fast build rule for target.
Aegis2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/build
.PHONY : Aegis2/fast

Source/AegisObject.o: Source/AegisObject.cpp.o
.PHONY : Source/AegisObject.o

# target to build an object file
Source/AegisObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisObject.cpp.o
.PHONY : Source/AegisObject.cpp.o

Source/AegisObject.i: Source/AegisObject.cpp.i
.PHONY : Source/AegisObject.i

# target to preprocess a source file
Source/AegisObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisObject.cpp.i
.PHONY : Source/AegisObject.cpp.i

Source/AegisObject.s: Source/AegisObject.cpp.s
.PHONY : Source/AegisObject.s

# target to generate assembly for a file
Source/AegisObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisObject.cpp.s
.PHONY : Source/AegisObject.cpp.s

Source/AegisSystems.o: Source/AegisSystems.cpp.o
.PHONY : Source/AegisSystems.o

# target to build an object file
Source/AegisSystems.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisSystems.cpp.o
.PHONY : Source/AegisSystems.cpp.o

Source/AegisSystems.i: Source/AegisSystems.cpp.i
.PHONY : Source/AegisSystems.i

# target to preprocess a source file
Source/AegisSystems.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisSystems.cpp.i
.PHONY : Source/AegisSystems.cpp.i

Source/AegisSystems.s: Source/AegisSystems.cpp.s
.PHONY : Source/AegisSystems.s

# target to generate assembly for a file
Source/AegisSystems.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/AegisSystems.cpp.s
.PHONY : Source/AegisSystems.cpp.s

Source/BaseSystem.o: Source/BaseSystem.cpp.o
.PHONY : Source/BaseSystem.o

# target to build an object file
Source/BaseSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/BaseSystem.cpp.o
.PHONY : Source/BaseSystem.cpp.o

Source/BaseSystem.i: Source/BaseSystem.cpp.i
.PHONY : Source/BaseSystem.i

# target to preprocess a source file
Source/BaseSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/BaseSystem.cpp.i
.PHONY : Source/BaseSystem.cpp.i

Source/BaseSystem.s: Source/BaseSystem.cpp.s
.PHONY : Source/BaseSystem.s

# target to generate assembly for a file
Source/BaseSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/BaseSystem.cpp.s
.PHONY : Source/BaseSystem.cpp.s

Source/CameraComponent.o: Source/CameraComponent.cpp.o
.PHONY : Source/CameraComponent.o

# target to build an object file
Source/CameraComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/CameraComponent.cpp.o
.PHONY : Source/CameraComponent.cpp.o

Source/CameraComponent.i: Source/CameraComponent.cpp.i
.PHONY : Source/CameraComponent.i

# target to preprocess a source file
Source/CameraComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/CameraComponent.cpp.i
.PHONY : Source/CameraComponent.cpp.i

Source/CameraComponent.s: Source/CameraComponent.cpp.s
.PHONY : Source/CameraComponent.s

# target to generate assembly for a file
Source/CameraComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/CameraComponent.cpp.s
.PHONY : Source/CameraComponent.cpp.s

Source/Component.o: Source/Component.cpp.o
.PHONY : Source/Component.o

# target to build an object file
Source/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Component.cpp.o
.PHONY : Source/Component.cpp.o

Source/Component.i: Source/Component.cpp.i
.PHONY : Source/Component.i

# target to preprocess a source file
Source/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Component.cpp.i
.PHONY : Source/Component.cpp.i

Source/Component.s: Source/Component.cpp.s
.PHONY : Source/Component.s

# target to generate assembly for a file
Source/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Component.cpp.s
.PHONY : Source/Component.cpp.s

Source/Material.o: Source/Material.cpp.o
.PHONY : Source/Material.o

# target to build an object file
Source/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Material.cpp.o
.PHONY : Source/Material.cpp.o

Source/Material.i: Source/Material.cpp.i
.PHONY : Source/Material.i

# target to preprocess a source file
Source/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Material.cpp.i
.PHONY : Source/Material.cpp.i

Source/Material.s: Source/Material.cpp.s
.PHONY : Source/Material.s

# target to generate assembly for a file
Source/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Material.cpp.s
.PHONY : Source/Material.cpp.s

Source/Mesh.o: Source/Mesh.cpp.o
.PHONY : Source/Mesh.o

# target to build an object file
Source/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Mesh.cpp.o
.PHONY : Source/Mesh.cpp.o

Source/Mesh.i: Source/Mesh.cpp.i
.PHONY : Source/Mesh.i

# target to preprocess a source file
Source/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Mesh.cpp.i
.PHONY : Source/Mesh.cpp.i

Source/Mesh.s: Source/Mesh.cpp.s
.PHONY : Source/Mesh.s

# target to generate assembly for a file
Source/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Mesh.cpp.s
.PHONY : Source/Mesh.cpp.s

Source/MeshRenderer.o: Source/MeshRenderer.cpp.o
.PHONY : Source/MeshRenderer.o

# target to build an object file
Source/MeshRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/MeshRenderer.cpp.o
.PHONY : Source/MeshRenderer.cpp.o

Source/MeshRenderer.i: Source/MeshRenderer.cpp.i
.PHONY : Source/MeshRenderer.i

# target to preprocess a source file
Source/MeshRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/MeshRenderer.cpp.i
.PHONY : Source/MeshRenderer.cpp.i

Source/MeshRenderer.s: Source/MeshRenderer.cpp.s
.PHONY : Source/MeshRenderer.s

# target to generate assembly for a file
Source/MeshRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/MeshRenderer.cpp.s
.PHONY : Source/MeshRenderer.cpp.s

Source/ObjectManager.o: Source/ObjectManager.cpp.o
.PHONY : Source/ObjectManager.o

# target to build an object file
Source/ObjectManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ObjectManager.cpp.o
.PHONY : Source/ObjectManager.cpp.o

Source/ObjectManager.i: Source/ObjectManager.cpp.i
.PHONY : Source/ObjectManager.i

# target to preprocess a source file
Source/ObjectManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ObjectManager.cpp.i
.PHONY : Source/ObjectManager.cpp.i

Source/ObjectManager.s: Source/ObjectManager.cpp.s
.PHONY : Source/ObjectManager.s

# target to generate assembly for a file
Source/ObjectManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ObjectManager.cpp.s
.PHONY : Source/ObjectManager.cpp.s

Source/Scene.o: Source/Scene.cpp.o
.PHONY : Source/Scene.o

# target to build an object file
Source/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Scene.cpp.o
.PHONY : Source/Scene.cpp.o

Source/Scene.i: Source/Scene.cpp.i
.PHONY : Source/Scene.i

# target to preprocess a source file
Source/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Scene.cpp.i
.PHONY : Source/Scene.cpp.i

Source/Scene.s: Source/Scene.cpp.s
.PHONY : Source/Scene.s

# target to generate assembly for a file
Source/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Scene.cpp.s
.PHONY : Source/Scene.cpp.s

Source/SceneSystem.o: Source/SceneSystem.cpp.o
.PHONY : Source/SceneSystem.o

# target to build an object file
Source/SceneSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/SceneSystem.cpp.o
.PHONY : Source/SceneSystem.cpp.o

Source/SceneSystem.i: Source/SceneSystem.cpp.i
.PHONY : Source/SceneSystem.i

# target to preprocess a source file
Source/SceneSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/SceneSystem.cpp.i
.PHONY : Source/SceneSystem.cpp.i

Source/SceneSystem.s: Source/SceneSystem.cpp.s
.PHONY : Source/SceneSystem.s

# target to generate assembly for a file
Source/SceneSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/SceneSystem.cpp.s
.PHONY : Source/SceneSystem.cpp.s

Source/Shader.o: Source/Shader.cpp.o
.PHONY : Source/Shader.o

# target to build an object file
Source/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Shader.cpp.o
.PHONY : Source/Shader.cpp.o

Source/Shader.i: Source/Shader.cpp.i
.PHONY : Source/Shader.i

# target to preprocess a source file
Source/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Shader.cpp.i
.PHONY : Source/Shader.cpp.i

Source/Shader.s: Source/Shader.cpp.s
.PHONY : Source/Shader.s

# target to generate assembly for a file
Source/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Shader.cpp.s
.PHONY : Source/Shader.cpp.s

Source/ShaderSource.o: Source/ShaderSource.cpp.o
.PHONY : Source/ShaderSource.o

# target to build an object file
Source/ShaderSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ShaderSource.cpp.o
.PHONY : Source/ShaderSource.cpp.o

Source/ShaderSource.i: Source/ShaderSource.cpp.i
.PHONY : Source/ShaderSource.i

# target to preprocess a source file
Source/ShaderSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ShaderSource.cpp.i
.PHONY : Source/ShaderSource.cpp.i

Source/ShaderSource.s: Source/ShaderSource.cpp.s
.PHONY : Source/ShaderSource.s

# target to generate assembly for a file
Source/ShaderSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/ShaderSource.cpp.s
.PHONY : Source/ShaderSource.cpp.s

Source/Texture.o: Source/Texture.cpp.o
.PHONY : Source/Texture.o

# target to build an object file
Source/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Texture.cpp.o
.PHONY : Source/Texture.cpp.o

Source/Texture.i: Source/Texture.cpp.i
.PHONY : Source/Texture.i

# target to preprocess a source file
Source/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Texture.cpp.i
.PHONY : Source/Texture.cpp.i

Source/Texture.s: Source/Texture.cpp.s
.PHONY : Source/Texture.s

# target to generate assembly for a file
Source/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Texture.cpp.s
.PHONY : Source/Texture.cpp.s

Source/Transform.o: Source/Transform.cpp.o
.PHONY : Source/Transform.o

# target to build an object file
Source/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Transform.cpp.o
.PHONY : Source/Transform.cpp.o

Source/Transform.i: Source/Transform.cpp.i
.PHONY : Source/Transform.i

# target to preprocess a source file
Source/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Transform.cpp.i
.PHONY : Source/Transform.cpp.i

Source/Transform.s: Source/Transform.cpp.s
.PHONY : Source/Transform.s

# target to generate assembly for a file
Source/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/Transform.cpp.s
.PHONY : Source/Transform.cpp.s

Source/glad.o: Source/glad.c.o
.PHONY : Source/glad.o

# target to build an object file
Source/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/glad.c.o
.PHONY : Source/glad.c.o

Source/glad.i: Source/glad.c.i
.PHONY : Source/glad.i

# target to preprocess a source file
Source/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/glad.c.i
.PHONY : Source/glad.c.i

Source/glad.s: Source/glad.c.s
.PHONY : Source/glad.s

# target to generate assembly for a file
Source/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/glad.c.s
.PHONY : Source/glad.c.s

Source/obj_loader.o: Source/obj_loader.cpp.o
.PHONY : Source/obj_loader.o

# target to build an object file
Source/obj_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/obj_loader.cpp.o
.PHONY : Source/obj_loader.cpp.o

Source/obj_loader.i: Source/obj_loader.cpp.i
.PHONY : Source/obj_loader.i

# target to preprocess a source file
Source/obj_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/obj_loader.cpp.i
.PHONY : Source/obj_loader.cpp.i

Source/obj_loader.s: Source/obj_loader.cpp.s
.PHONY : Source/obj_loader.s

# target to generate assembly for a file
Source/obj_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aegis2.dir/build.make CMakeFiles/Aegis2.dir/Source/obj_loader.cpp.s
.PHONY : Source/obj_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Aegis2"
	@echo "... Source/AegisObject.o"
	@echo "... Source/AegisObject.i"
	@echo "... Source/AegisObject.s"
	@echo "... Source/AegisSystems.o"
	@echo "... Source/AegisSystems.i"
	@echo "... Source/AegisSystems.s"
	@echo "... Source/BaseSystem.o"
	@echo "... Source/BaseSystem.i"
	@echo "... Source/BaseSystem.s"
	@echo "... Source/CameraComponent.o"
	@echo "... Source/CameraComponent.i"
	@echo "... Source/CameraComponent.s"
	@echo "... Source/Component.o"
	@echo "... Source/Component.i"
	@echo "... Source/Component.s"
	@echo "... Source/Material.o"
	@echo "... Source/Material.i"
	@echo "... Source/Material.s"
	@echo "... Source/Mesh.o"
	@echo "... Source/Mesh.i"
	@echo "... Source/Mesh.s"
	@echo "... Source/MeshRenderer.o"
	@echo "... Source/MeshRenderer.i"
	@echo "... Source/MeshRenderer.s"
	@echo "... Source/ObjectManager.o"
	@echo "... Source/ObjectManager.i"
	@echo "... Source/ObjectManager.s"
	@echo "... Source/Scene.o"
	@echo "... Source/Scene.i"
	@echo "... Source/Scene.s"
	@echo "... Source/SceneSystem.o"
	@echo "... Source/SceneSystem.i"
	@echo "... Source/SceneSystem.s"
	@echo "... Source/Shader.o"
	@echo "... Source/Shader.i"
	@echo "... Source/Shader.s"
	@echo "... Source/ShaderSource.o"
	@echo "... Source/ShaderSource.i"
	@echo "... Source/ShaderSource.s"
	@echo "... Source/Texture.o"
	@echo "... Source/Texture.i"
	@echo "... Source/Texture.s"
	@echo "... Source/Transform.o"
	@echo "... Source/Transform.i"
	@echo "... Source/Transform.s"
	@echo "... Source/glad.o"
	@echo "... Source/glad.i"
	@echo "... Source/glad.s"
	@echo "... Source/obj_loader.o"
	@echo "... Source/obj_loader.i"
	@echo "... Source/obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

